{{- if .Values.server.configEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" "cm") | nindent 4 }}
  {{- if .Values.server.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.server.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
  url: https://argocd.example.com
{{- end }}